### ISSUE TITLE
Including jet template as template variable

### ISSUE THREAD

**Issue by JesseRyan** [CloudyKit/jet#104]
Is this possible or am I going crazy?

Seems like this type of nesting should be supported:
```

{{block StarScreamTemplate(commands="", megatronsOrders="", myOwnWill="", subTemplates={{include SoundWaveTemplate(music="", orders="")}},{{include UnicronTempalte(worlds="", orders="")}} }}

{{yield StarScreamTemplate(commands="get Optimus", megatronsOrders="stay at base", myOwnWill="infinite")}}
```

Perhaps there is already a way to do this?

**Comment by annismckenzie** [comment]
No, that won't work:
1. You can use (and yield) templates in your blocks, yes. But including them in your block definition will probably not work. Plus, even if it did, it would be static because you can't change the invocation of the `subTemplates` parameter when yielding. Either create separate blocks in another template and import it into this template, then use the blocks by yielding them in your block above (`StarScreamTemplate`) or include them at the appropriate position in your block definition's content (see https://github.com/CloudyKit/jet/wiki/3.-Jet-template-syntax#defining-a-block in the wiki).

Aaaaah, now I see what you wrote. The last part in the first line is supposed to be the content of the block?

```handlebars
<!-- define the block -->
{{block StarScreamTemplate(commands="", megatronsOrders="", myOwnWill=""}}
  <!-- your subTemplates parameter won't work, you may include it here or
       push it to another file, make the template a block, include the file and
       use the block here by yielding it -->
  <!-- the last part of your block definition above I guess should be the
       block content because it wasn't declared as a parameter? -->
  {{include UnicronTempalte(worlds="", orders="")}}
{{end}}

<!-- produce output by yielding the block -->
{{yield StarScreamTemplate(commands="get Optimus", megatronsOrders="stay at base", myOwnWill="infinite")}}
```

If I got it wrong I'll need some more information. How should the output look? Otherwise, a parse error or a runtime error are helpful as well. :)

**Comment by JesseRyan** [comment]
```
{{block StarScreamTemplate(commands="", megatronsOrders="", myOwnWill="", subTemplates={{include SoundWaveTemplate(music="", orders=""), include UnicronTemplate(music="", orders="")}}
 {
 "StarScream":
    {
    "commands":"{{id}}",
    "megatronsOrders":"{{tag}}",
    "myOwnWill":"{{coord}}", {* string: "width, height" *}
    "subTemplates":[ {{range subTemplates}}{{ yield template()}},{{end}}]
    }
}
{{end}}
```

{* which would invoke something along the lines below *}
{* I am not using correct syntax, but more or less, trying to communicate the idea *}

```

 {
 "StarScream":
    {
    "commands":"{{id}}",
    "megatronsOrders":"{{tag}}",
    "myOwnWill":"{{coord}}", {* string: "width, height" *}
    "subTemplates":[ {{yield SoundWaveTemplate(music="", orders=""), yield UnicronTemplate(music="", orders="") }}]
    }
}
```

Hey thank you for quickly responding. This is much appreciated.

**Comment by JesseRyan** [comment]
Ended up having to do something along the lines of:
```
{* figure out how to make actual optional variables for testing, not including one will cause gophers to panic *}
{{import "../Container.jet"}}
{{import "../Image.jet"}}
{{import "../Label.jet"}}
{{import "../Close.jet"}}
{{block Template(width="125", height="125")}}
{{yield Container(has_children=true)}} 
{{yield Image()}},
{{yield Label()}}
{{yield Close()}} 
{{end}}
```

**Comment by annismckenzie** [comment]
Nice, that looks good!

**Comment by annismckenzie** [comment]
Close the issue please? :)
