### ISSUE TITLE
Context leak on recover

### ISSUE THREAD

**Issue by japettyjohn** [CloudyKit/jet#117]
I noticed a fix given in [this fork](https://github.com/kabukky/jet/commit/6f7ec1b8f0c603d6740d016409a230c57829b100) for a [line in eval.go](https://github.com/CloudyKit/jet/blob/master/eval.go#L224) indicating that this potentially leaks variables between executions.

This should be reviewed for severity and potentially merging here.

**Comment by kabukky** [comment]
That's my fork.
The bug seems to only occur if the template execution panics (e. g. a panic when accessing a variable that isn't set).
You are recovering from these panics inside the `Runtime.recover` method. However, the Runtime (state) isn't properly reset in that case.

My quick fix was to not put the state back into the pool, but this will result in a new Runtime being created every time (and the pool being useless).

What would be the proper way to reset the state? Calling `Runtime.releaseScope`panics (probably because the scope parent isn't available in this case - so that isn't an option.

**Comment by kabukky** [comment]
@annismckenzie Do you know how I would go about resetting the scope in this case? I'd like to implement a correct fix.

**Comment by annismckenzie** [comment]
Sadly, I don’t know that part of the code base well. I’ve mostly helped out in this project with documentation and writing smaller features. :(

**Comment by kabukky** [comment]
Here's how I've fixed it in our fork now: https://github.com/kabukky/jet/commit/192d97b8d685b3c946b65bde42fa41fa0a297890
