### ISSUE TITLE
complex if statements

### ISSUE THREAD

**Issue by marcelloh** [CloudyKit/jet#145]
Can you add some examples of complexer if statements to the manual?

I only found 
{{if expression}}
{{end}}

But I can't figure out how this expression part works when a more "complex" expression is needed.

like:
if a == "A" && b == "B"
(because I don't know how this notation goes)
same goes for "||"

like:
if a > 16
I get: unexpected "&gt" in if

like:
{{ if .Meta["teaser"] == "" }} or {{ if .Meta["teaser"] != "" }}
I get: reflect: call of reflect.Value.IsNil on string Value

**Comment by sauerbraten** [comment]
`{{ a == "A" && b == "B" }}` is a perfectly fine expression and would render `true` or `false` into your output. Using it as condition in an if is also fine: `{{ if a == "A" && b == "B" }} a is A, b is B {{ else }} something's fishy {{end}}`

>  I get: unexpected "&gt" in if
In that case, something HTML-escaped your jet template. If you open it in a text editor and it really says ">" and not "&gt;", then there might be some processing step happening before you give the contents to jet?

>  I get: reflect: call of reflect.Value.IsNil on string Value
This looks like a bug, although one that may have been fixed in the current master branch. Can you tell us what `.Meta` is? What type, and what does it contain?
