### ISSUE TITLE
render as HTML?

### ISSUE THREAD

**Issue by arminschleicher** [CloudyKit/jet#153]
Hey there is it possible to render the return value of a template function as HTML instead of plain text? If so, how? Thanks!

**Comment by sauerbraten** [comment]
I'm not sure I understand what you mean. If you have a function `foo()` that returns a string, `{{ foo() }}` would render the string while escaping characters that wouldn't be safe in HTML as-is. What do you want it to do?

**Comment by sauerbraten** [comment]
For example, let's say `foo()` returns `"5 > 3"`. `{{ foo() }}` will output `5 &gt; 3`.

**Comment by arminschleicher** [comment]
Thanks for the fast reply! I render my content via a function `t("contentKey")` which takes care of i18n. Say i would like to render a longer paragraph and `{{ t("myParagraph")}}` returns `Blablabla<br/>Blablabla`, i would like the template engine to interpret it as HTML and render the `<br/>` as a line break and not as `<br/>`. How would i achieve that?

**Comment by sauerbraten** [comment]
I think you are asking how to prevent jet from escaping HTML for you, because you already render the final HTML in your function? in that case, you can pipeline the result of your function call into the `raw` or `unsafe` built-in (they're two names for the same thing): `{{ t("myParagraph") | raw }}`

See https://github.com/CloudyKit/jet/wiki/3.-Jet-template-syntax#pipelining for more information on pipelining, and it has exactly the raw/unsafe example you need. 👍

**Comment by sauerbraten** [comment]
And then there is https://github.com/CloudyKit/jet/wiki/5.-Advanced-Customization#custom-escape-handling-using-safewriter for very advanced needs, if you find yourself needing even more control over escaping etc.

**Comment by arminschleicher** [comment]
Aaaaah got it! Awesome thank yoou!!
