### ISSUE TITLE
Release v4

### ISSUE THREAD

**Issue by razonyang** [CloudyKit/jet#157]
Months have passed since the last version, would you please draft a new version.

**Comment by codexuexi** [comment]
![image](https://user-images.githubusercontent.com/28785644/86367788-f80aa500-bcae-11ea-9ede-75b1b45d1f01.png)
Can't pull v3.0.0
I am a novice and I don’t know what caused the problem

**Comment by sauerbraten** [comment]
@codexuexi `go get github.com/CloudyKit/jet/v3@latest` should get you v3. You will also have to use `github.com/CloudyKit/jet/v3` wherever you import jet.

**Comment by sauerbraten** [comment]
@razonyang v4 is coming! I just want to make sure the changes are documented, especially breakinng ones.

**Comment by razonyang** [comment]
@codexuexi What is the output of the following command?

```shell
go get -u github.com/CloudyKit/jet/v3
```

No output means pull successfully. You also need to change Jet's import path as `github.com/CloudyKit/jet/v3`.

BTW, you should open a new issue for discussing since it is unrelated to the original topic.

**Comment by codexuexi** [comment]
@razonyang  
Thank you, you can use this command
I use
```
go get -u github.com/CloudyKit/jet@v3
```
@sauerbraten I'm looking forward to it, but in fact, code completion and highlighting are very popular among people like `IntelliJ` and `Visual Studio Code`

**Comment by razonyang** [comment]
@sauerbraten That's great!

BTW, `v3.0.0` seems unable to parse `nil` variable, it works fine in `master`, could you please confirm this bug has been fixed?

```go
set := jet.NewHTMLSet("./")
t, _ := set.GetTemplate("index.tmpl")
buf := &bytes.Buffer{}
vars := jet.VarMap{}
vars.Set("user", nil)
if err := t.Execute(buf, vars, nil); err != nil {
	log.Fatal(err)
}

fmt.Println(buf.String())
```

```html
{{ if user }}
Authenticated
{{ else }}
Guest
{{ end }}
```

`v3.0.0`:

```text
Jet Runtime Error ("index.tmpl":1): identifier "user" is not available in the current scope map[user:<invalid Value>]
exit status 1
```

`v3.0.0@master`:

```text
Guest
```

**Comment by sauerbraten** [comment]
@codexuexi: the command you use is simply wrong.

In Go, major versions > 1 require the module import path to be different. Jet v3's module import path is `github.com/CloudyKit/jet/v3`, not `github.com/CloudyKit/jet`.

You have to use something like I or @razonyang showed you in order to use version 3 or later of Jet.

I am also not sure what you mean with this:

> but in fact, code completion and highlighting are very popular among people like IntelliJ and Visual Studio Code

I never said anything different, I never even touched that subject. Do you have in issue with IDE support? If so, please open an issue, or comment in one that's related to IDE support.

**Comment by sauerbraten** [comment]
@razonyang: But you said yourself that it works on the current master? Didn't you confirm the bug has been fixed yourself?

**Comment by razonyang** [comment]
@sauerbraten Yes, it works on the current master, but I didn't look into the source code, I am not very sure that it has been fixed.

**Comment by sauerbraten** [comment]
I guess you mean you're not sure the bug is fixed, even though your example code works now?

It's fixed: compare https://github.com/CloudyKit/jet/blob/v3.0.0/eval.go#L1096 to https://github.com/CloudyKit/jet/blob/master/eval.go#L1074.

In v3.0.0, any identifier evaluating to `nil` would cause a panic, because Resolve() returned the reflect equivalent of `nil` in case it doesn't find anything, but also when the value was simply set to `nil`. Outside of Resolve(), there was no way to know which of these two things happened.

Now, `resolve()` returns an error if the variable can't be found anywhere, which means we know what happened when evaluating `users` in your example: it was resolved just fine, and we let `if` check wether it's truthy (which it isn't).

Hope this puts you at ease! 👍

**Comment by sauerbraten** [comment]
Here we go! https://github.com/CloudyKit/jet/releases/tag/v4.0.0
