### ISSUE TITLE
Whitespace Removal

### ISSUE THREAD

**Issue by tooolbox** [CloudyKit/jet#172]
Just a thought, would like feedback from @sauerbraten whenever possible 😉 

One thing that Go Templates has over Jet is the ability to [trim preceding and trailing whitespace](https://golang.org/pkg/text/template/#hdr-Text_and_spaces) using `{{- ` and ` -}}`.  This comes in handy sometimes and would be cool to have in Jet (not necessarily with that exact syntax, but I haven't thought hard about a better alternative).

Since at this point you're possibly the most familiar with Jet's inner workings, I'm interested in your take on how feasible this would be to implement?

**Comment by sauerbraten** [comment]
I'd really like Jet to have this feature, too. At my job, we use a hacky regex-replacement after running templates through Jet, so it would be great to have for us, too. Regarding feasibility: Since Jet's lexing and parsing is based off Go's template package, this should be possible. I guess as a start we could look at how the template package does it, and compare this to our lex.go and parse.go. If you want, go ahead and try and implement it, or wait until later this week and I might have time to look at this :)

**Comment by tooolbox** [comment]
Hehe, sounds like a lovely regex 😉 

Okay great, if I get a chance I'll take a stab.
