### ISSUE TITLE
How to handle error in custom functions?

### ISSUE THREAD

**Issue by razonyang** [CloudyKit/jet#174]
Hi, I follow the [wiki](https://github.com/CloudyKit/jet/wiki/5.-Advanced-Customization#fast-functions) to create a custom function:

```go
set.AddGlobalFunc("foo", func(args jet.Arguments) reflect.Value {
    v, err := doStaff()
    if err != nil {
         // handle error
    }
    
    return reflect.ValueOf(v) 
})
```

What is the proper way to handle error? Should I use `panic`?

Does Jet provide a way to handle function call errors globally, so that we can define function like:

```go
func(args jet.Arguments) (reflect.Value, error) {
    v, err := doStaff()
    if err != nil {
         return reflect.Value{}, err
    }
    
    return reflect.ValueOf(v), nil
}
```

**Comment by sauerbraten** [comment]
Jet doesn't support your function returning an error.

Whether you should use panic or not depends on what you want to happen: if the error means you can't continue rendering the template, use panic. Jet will recover from it and show you where the error occured, instead of rendering the template. If it's not a fatal error, you can log that something went wrong and then return a default (valid) value that will allow Jet to continue rendering your template.

Does that answer your question?

**Comment by razonyang** [comment]
Got it, thanks!
