### ISSUE TITLE
Add defaultExtensions to the Set struct 

### ISSUE THREAD

**Issue by jhsx** [CloudyKit/jet#19]
This would simplify template loading, by default, defaultExtensions would be .html.jet .jet. then when trying to load a template "dashboard/main" Jet would first check for "dashboard/main", then "dashboard/main.html.jet" and lastly "dashboard/main.jet" none found then return an error.

this also need to work with relative paths #16 

@annismckenzie, what do you think about this feature ?

**Comment by jhsx** [comment]
Done 👍

**Comment by annismckenzie** [comment]
I wanted to post this comment yesterday and somehow got side-tracked. Still, here it is (even if you're done – which is awesome!):

This would be a nice convenience feature – it's also backwards-compatible and doesn't incur a performance penalty because it only happens once.

Where this would be really useful, though, is in a web framework that could load a template by also taking the content type into account (JSON/XML/YAML) and look for `dashboard/main.[html,xml,yaml].jet`.

**Comment by jhsx** [comment]
Good to know, another use case, is to add a more clean template invocation in frameworks.
ex:
```go
c.Render("catalog/products",c.ProductContext)
```

I forgot to add the method to add new default Extensions, will do in the next commit.
Thanks for your feedback.
