### ISSUE TITLE
how to call template function?

### ISSUE THREAD

**Issue by dxvgef** [CloudyKit/jet#43]
I use a template variable to send a function, how to call it in the template?

``` Go
func Full() string {
	return "ok"
}

data := make(map[string]interface{})
data["Full"]= Full
```

**Comment by jhsx** [comment]
Function calls work same way as in go just do  ``` Func()  ```

**Comment by dxvgef** [comment]
Why Full() output is a memory address:

```Go
func Full() string {
	return "ok"
}

func Index(ctx echo.Context) error {
	data := make(map[string]interface{})
	data["Full"]= Full
	return ctx.Render(200, "index.jet", data)
}
```

```HTML
<body>
{{.Full}}
</body>
```

**Comment by annismckenzie** [comment]
Instead of `{{call .Full}}` do `{{ Full() }}` and you're done.

**Comment by dxvgef** [comment]
@annismckenzie Sorry, I can't work:

```Go
package main

import (
	"os"
	"github.com/CloudyKit/jet"
)

func Func() string {
	return "ok"
}

func main() {
	data := make(map[string]interface{})
	data["Func"] = Func
	r, err :=jet.NewHTMLSet("./").GetTemplate("test.jet")
	if err != nil {
		panic(err.Error())
	}
	r.Execute(os.Stdout, nil, data)
}
```
**test.jet:**
```HTML
print:{{Func()}}
```

**Output:**
`print:`

**Comment by annismckenzie** [comment]
Well no, that's not going to work. You're mistaking the `data` part and the variable map part. The var map should hold your functions as well as variables you need when rendering a template. The data part is just an `interface{}` and should usually be used to pass the main object a template is concerned with – if you're rendering a user edit form then it'd be a User struct.

Here, this will work:
```go
package main

import (
	"os"

	"github.com/CloudyKit/jet"
)

func Func() string {
	return "ok"
}

func main() {
	vars := jet.VarMap{}
	vars.Set("Func", Func)
	r, err := jet.NewHTMLSet("./").GetTemplate("test.jet")
	if err != nil {
		panic(err.Error())
	}
	r.Execute(os.Stdout, vars, nil)
}
```

Please take a look at the documentation in the wiki – here: https://github.com/CloudyKit/jet/wiki/Rendering-templates and here: https://github.com/CloudyKit/jet/wiki/Jet-template-syntax.

The correct syntax for calling a function when the data is a `map[string]interface{}` in a template would have been: `{{ .["Func"]() }}`. That's because the data is treated as an interface and the dot in the template represents that object. So your object is a map, hence the map key lookup. Although I wouldn't recommend doing that you might have found a bug there (»panic: template: test.jet:1: unexpected "(" in command«), I'll add a unit test and open an issue. Thanks!

**Comment by dxvgef** [comment]
Thank you, so jet does not support the introduction of custom functions in the form of template variables?

**Comment by annismckenzie** [comment]
I'm not following. What exactly are you trying to accomplish?

**Comment by dxvgef** [comment]
I use the echo framework, its interface function Render() can only be imported interface{} template variables, no chance to introduce other parameters, I think of other ways, thank you!

**Comment by jhsx** [comment]
@dxvgef {{ .Full() }} should work please check for errors, maybe we have a bug.

**Comment by dxvgef** [comment]
@jhsx I copied the @annismckenzie code, and use the `{{.Full(} }}` in the template but no output.
Then I changed the `Main()` function into this, still no output:

**main.go**
```Go
package main

import (
	"os"
	
	"github.com/CloudyKit/jet"
)

func Full() string {
	return "ok"
}

/*
func main() {
	vars := jet.VarMap{}
	vars.Set("Full", Full)
	r, err := jet.NewHTMLSet("./").GetTemplate("test.jet")
	if err != nil {
		panic(err.Error())
	}
	r.Execute(os.Stdout, vars, nil)
}
*/

func main() {
	data := make(map[string]interface{})
	r, err := jet.NewHTMLSet("./").GetTemplate("test.jet")
	if err != nil {
		panic(err.Error())
	}
	r.Execute(os.Stdout, nil, data)
}
```

**test.jet**
```
{{.Full()}}
```

**Comment by annismckenzie** [comment]
First, `r.Execute` has an error return value that contains errors when rendering the template. In your example, it would have returned: `Jet Runtime Error("test.jet":0): there is no field or method "Full" in nil`. Your example is wrong because you're trying to call the `Full` method on the context which is the last parameter passed to `r.Execute` and is `nil` in your code. Doing `{{ Full() }}` in that example would work.

Now, the second main method has a different problem. You're still trying to call the `Full()` method on the context and you passed a `map[string]interface{}` as the context. Apart from the fact that it's empty in your code, it just won't work. Here's what you can do, though. I combined both possible solutions into one so you can see the difference:

#### main.go
```go
package main

import (
	"os"

	"github.com/CloudyKit/jet"
)

func Full() string {
	return "ok"
}

type Data struct{}

func (d *Data) Full() string {
	return "ok from struct"
}

func main() {
	vars := jet.VarMap{}
	vars.Set("Full", Full)
	r, err := jet.NewHTMLSet("./").GetTemplate("test.jet")
	if err != nil {
		panic(err.Error())
	}
	data := &Data{}
	err = r.Execute(os.Stdout, vars, data)
	if err != nil {
		panic(err.Error())
	}
}
```

#### test.jet
```HTML
{{ Full() }} {* called on the var map *}

{{ .Full() }} {* called on the Data struct *}
```

This compiles, works and returns:
```
ok

ok from struct
```

Coming back to your original problem with the Echo framework – here's a quick example of how this could work:

#### main.go
```go
package main

import (
	"io"

	"github.com/CloudyKit/jet"
	"github.com/labstack/echo"
)

func Full() string {
	return "ok"
}

type Data struct{}

func (d *Data) Full() string {
	return "ok from struct"
}

type JetRenderer struct {
	set *jet.Set
}

// Render satisfies the Echo.Renderer interface.
func (r *JetRenderer) Render(w io.Writer, name string, data interface{}, c echo.Context) error {
	t, err := r.set.GetTemplate(name)
	if err != nil {
		return err
	}
	vars, ok := data.(jet.VarMap)
	if !ok { // data passed wasn't a var map
		vars = jet.VarMap{}
	}
	err = t.Execute(w, vars, nil)
	if err != nil {
		// render an error response?
		// log the error?
		// up to you
	}
	return nil
}

func main() {
	s := jet.NewHTMLSet("./")
	s.AddGlobal("Full", Full)
	s.SetDevelopmentMode(true) // set this to false in production; it reloads templates while developing

	e := echo.New()
	e.Renderer = &JetRenderer{set: s}
	e.GET("/", welcome)
	e.Logger.Fatal(e.Start(":4000"))
}

func welcome(c echo.Context) error {
	vars := jet.VarMap{}
	vars.Set("testObject", &Data{})
	return c.Render(200, "welcome.jet", vars)
}
```

#### welcome.jet
```HTML
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Welcome!</title>
  </head>
  <body>
    {{ Full() }}<br />

    {{ testObject.Full() }}
  </body>
</html>
```

Yes, you need the type assertion to unbox the variable map from the interface-typed data parameter but that's not too bad.

Can you work with that?

**Comment by dxvgef** [comment]
@annismckenzie Understand that it can now work, I try again, thank you!

**Comment by jhsx** [comment]
@dxvgef @annismckenzie  maybe your code was not working before cause of a case that was not handled inside getValue, i can reproduce with a modified version of your code. I fixed and will push the modifications.
