### ISSUE TITLE
Error 500 if block name is "content"

### ISSUE THREAD

**Issue by toby3d** [CloudyKit/jet#65]
I always get error 500 if I try execute template which contains block with name `content()` like that:
```
{{yield content()}}
...
{{block content()}} {{end}}
```
But after change name all is okay. Tested in enabled development mode.

**Comment by annismckenzie** [comment]
Take a look at the docs here: https://github.com/CloudyKit/jet/wiki/Jet-template-syntax#new-in-v2-local-block-variables-with-defaults-and-wrapping-at-invocation-time. This looks like a minor bug in the parser because it could potentially distinguish between `{{yield content()}}` and `{{yield content}}` but I'm not sure it'd be wise to do so.

I'd suggest disallowing the definition of a `content` block via `{{block content()}} {{end}}` when parsing templates and documenting this as such. /cc @jhsx

**Comment by jhsx** [comment]
@toby3d ```content``` is a keyword in the lexer|parser and is part of the template language.
@annismckenzie Agree we should disallow the ```content``` in a block definition.

**Comment by annismckenzie** [comment]
I'm gonna try to make it so that the parsing fails and think about how we could provide a tool that would check that templates are at least parsing without errors so this doesn't blow up at runtime.
