### ISSUE TITLE
Comparing string with integer fails without error

### ISSUE THREAD

**Issue by mvrhov** [CloudyKit/jet#83]
I know that the go is strongly typed language but template engine needn't be. 
IMO the following should succeed.
ATM it just dies without an error. You just get the incomplete template.
`{{ if "2006" < 2018 }}foooooooo{{end}}`

I don't know if this is separate or the same problem:
```golang
	View.AddGlobal("toInt", func(str string) int {
		i, _ := strconv.Atoi(str)
		return i
	})
```
`{{ if "2006"|toInt < 2018 }}foooooooo{{end}}` Doesn't work, it has to be rewritten as `{{ if toInt("2006") < 2018 }}foooooooo{{end}}` Which seems to be another inconsistency.
Where the larger example would be `{{ if date()|date:"2006"|toInt > 2018 }}` where neither form works.
`{{ if toInt(date()|date:"2006") > 2018 }}`

**Comment by annismckenzie** [comment]
Well, underneath Jet is a parser and lexer that execute Go code so building in relaxed typing isn't going to happen. That said, I noticed that Jet sometimes doesn't provide one with a clear error message. /cc @jhsx

**Comment by sauerbraten** [comment]
Pipelining (as you want to do in `{{ if "2006"|toInt < 2018 }}foooooooo{{end}}`) is a feature on action node level, i.e. immediately inside `{{` and `}}`, and will not be supported inside logical expressions, because parsing those would grow to complex. Function calls are enough inside a condition IMO.
